/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: process.env.REACT_APP_REGION,
  aws_cognito_region: process.env.REACT_APP_REGION,
  aws_user_pools_id: process.env.REACT_APP_USER_POOL_ID,
  aws_user_pools_web_client_id: process.env.REACT_APP_USER_POOL_CLIENT_ID,

  aws_cloud_logic_custom: [
    {
      name: process.env.REACT_APP_API_NAME,
      endpoint: process.env.REACT_APP_API_URL,
      region: process.env.REACT_APP_REGION,
    },
  ],
};

export default awsmobile;
